### ISSUE TITLE
[osx] screeninfo.common.ScreenInfoError: No enumerators available

### ISSUE THREAD

**Issue by hairesis** [Evidlo/remarkable_mouse#39] opened 2020-10-31 10:58 UTC
Hello, I've come across a weird issue on OSX:

Osx: 10.14.6
python: 3.7 (and 3.9) (installed with brew)
command: remouse --address 192.168.0.178 --key ~/.ssh/remarkable

Error:
`screeninfo.common.ScreenInfoError: No enumerators available`

Digging deeper I found out the error is raised from 
`ns_framework = autoclass('NSString').stringWithUTF8String_(framework)` 
in dependency's dependency of `screeninfo`: pyobjus .
```
homebrew/lib/python3.7/site-packages/pyobjus/dylib_manager.py", line 185, in load_framework
ns_framework = autoclass('NSString').stringWithUTF8String_(framework)
File "pyobjus/pyobjus.pyx", line 475, in pyobjus.ObjcMethod.__call__
File "pyobjus/pyobjus_conversions.pxi", line 240, in pyobjus.convert_cy_ret_to_py
File "pyobjus/pyobjus_conversions.pxi", line 181, in pyobjus.convert_to_cy_cls_instance
File "pyobjus/pyobjus.pyx", line 711, in pyobjus.autoclass
File "pyobjus/pyobjus.pyx", line 598, in pyobjus.resolve_super_class_methods
File "pyobjus/pyobjus.pyx", line 514, in pyobjus.class_get_methods
File "pyobjus/pyobjus.pyx", line 506, in pyobjus.objc_method_to_py
File "pyobjus/pyobjus.pyx", line 226, in pyobjus.ObjcMethod.__init__
File "pyobjus/type_enc.pxi", line 13, in pyobjus.parse_signature
File "pyobjus/type_enc.pxi", line 2, in pyobjus.seperate_encoding
IndexError: list index out of range
```

Packages installed:
```
python3.7 -m pip freeze
bcrypt==3.2.0
cffi==1.14.3
cryptography==3.2.1
Cython==0.29.21
libevdev==0.9
paramiko==2.7.2
pycparser==2.20
PyNaCl==1.4.0
pynput==1.7.1
pyobjc-core==6.2.2
pyobjc-framework-Cocoa==6.2.2
pyobjc-framework-Quartz==6.2.2
pyobjus==1.1.0
remarkable-mouse==5.2.1
screeninfo==0.6.6
six==1.15.0
```

The problem only happens when it is called in remouse. Following code in an interpreter just works:
```
from screeninfo import get_monitors
for m in get_monitors():
    print(str(m))
``` 
Any lead for me to further investigate what's going on?

**Comment by Evidlo** [comment] 2020-11-01 03:15
https://github.com/Evidlo/remarkable_mouse/issues/10

If you could figure out why screeninfo doesn't work on OSX, that would be great.  I've been trying to get someone to do that for over a year now.

**Comment by pierrejacob** [comment] 2020-11-01 09:07
Hi,
not sure if it's helpful at all but upon replacing 
  monitor = get_monitors()[args.monitor]
by 
  monitor = Monitor(
            x=10,
            y=10,
            width=1800,
            height=900
        )
in pynput.py I got the script to work on OSX. And it's super useful to me, so thanks a lot Evidlo!

**Comment by Henni** [comment] 2020-11-10 20:33
screeninfo collides with pynput
On my machine screeninfo works:
```
$ python3
>>> from screeninfo import get_monitors
>>> get_monitors()
[Monitor(x=0, y=0, width=1680, height=1050, width_mm=None, height_mm=None, name=None), Monitor(x=1680, y=0, width=3200, height=1800, width_mm=None, height_mm=None, name=None)]
```

If pynput is imported before importing screeninfo breaks:
```
$ python3
>>> from pynput.mouse import Button, Controller
>>> from screeninfo import get_monitors
>>> get_monitors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hendrik.leppelsack/Library/Python/3.9/lib/python/site-packages/screeninfo/screeninfo.py", line 37, in get_monitors
    raise ScreenInfoError("No enumerators available")
screeninfo.common.ScreenInfoError: No enumerators available
```

No idea if this can be fixed here.
But screeninfo can be rewritten to use AppKit instead of pyobjus  as commented here https://github.com/Evidlo/remarkable_mouse/pull/8#issuecomment-519240077

I'm working on a PR for screeninfo.

**Comment by Evidlo** [comment] 2020-11-11 16:30
@Henni Maybe it would make sense to file an issue with pynput to fix the underlying problem?

**Comment by Henni** [comment] 2020-11-12 15:43
Anyone with a Mac might want to review my PR to get this fixed:
https://github.com/rr-/screeninfo/pull/42

@Evidlo I can escalate this to pynput, but haven't figured out what causes it on their side.

**Comment by funkeyfreak** [comment] 2020-11-22 23:47
@Henni, do you need anyone with a mac, or someone affiliated with this repo? I'm more than happy to take a stab

**Comment by Evidlo** [comment] 2020-11-23 07:37
@funkeyfreak It seems like that PR is being blocked because were unsure if AppKit is available by default on OSX.  It would help if you could provide another data point.

**Comment by Evidlo** [comment] 2020-12-27 20:03
https://github.com/rr-/screeninfo/pull/42 is now merged.  Can someone confirm if this is still an issue?

**Comment by pascalw** [comment] 2020-12-28 14:40
@Evidlo I can confirm that with screeninfo 0.6.7 it works on macOS! 🎉

**Closed** 2020-12-28 19:19 UTC
